export const CLIENT_RTC_EVENT = 'CLIENT_RTC_EVENT';
export const SERVER_RTC_EVENT = 'SERVER_RTC_EVENT';

export const CLIENT_USER_EVENT = 'CLIENT_USER_EVENT';
export const SERVER_USER_EVENT = 'SERVER_USER_EVENT';

export const CLIENT_USER_EVENT_LOGIN = 'CLIENT_USER_EVENT_LOGIN'; // 登录

export const SERVER_USER_EVENT_UPDATE_USERS = 'SERVER_USER_EVENT_UPDATE_USERS';

export const CLIENT_USER_EVENT_SEND_MESSAGE="CLIENT_USER_EVENT_SEND_MESSAGE"
export const SERVER_USER_EVENT_BROADCAST_MESSAGE= 'SERVER_USER_EVENT_BROADCAST_MESSAGE';

export const SIGNALING_OFFER = 'SIGNALING_OFFER';
export const SIGNALING_ANSWER = 'SIGNALING_ANSWER';
export const SIGNALING_CANDIDATE = 'SIGNALING_CANDIDATE';

